import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} grid min-h-screen grid-cols-[auto_1fr] justify-center`}
      >
        <div className="w-80">
          <Sidebar />
        </div>
        <main className="">
          <div className="fixed bg-[#fff] z-20 w-full h-16 border-b border-[#e3e3e3]"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
